default:
  image: node:14.17

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm

stages:
  - install
  - build

install:
  stage: install
  script:
    - npm install --cache .npm

build-frontend:
  stage: build
  script:
    - npm -v #run build -w frontend --cache .npm

build-worker:
  stage: build
  script:
    - npm -v #run build -w worker --cache .npm