services:
     
  leofea:
    build: ./services/leofea
    command: python main.py
    volumes:
      - ./services/leofea:/app
    ports:
      - 5000:5000

  codeaster:
    build: ./services/codeaster
    command: python main.py
    volumes:
      - ./services/codeaster:/app
    ports:
      - 5001:5000

  # openfoam:
  #   build: ./services/openfoam
  #   command: python3 main.py
  #   volumes:
  #     - ./services/openfoam:/root
  #   ports:
  #     - 5002:5000

  paraview:
    build: ./services/paraview
    command: python main.py
    volumes:
      - ./services/paraview:/app
    ports:
      - 5003:5000
      