classDiagram

    direction LR

    class Model {
        name: string
    }

    class Assembly {
    }

    class Brick {
        mesh: Mesh
    }

    class Reference {
        color?: Color
        position: Vector
        orientation: Matrix
    }

    class File {
        name: string
    }

    File "1"*--"1..*" Assembly: assemblies

    Model <|-- Assembly: is a

    Assembly "1"*--"*" Reference: children

    Reference ..> Model

    Model <|-- Brick: is a