classDiagram
    direction LR
    
    class Sqlite
    class Postgres
    class React
    class Recharts
    class Three
    class Nest
    class Nodemailer
    class TypeORM
    class Aedes

    class Common
    class Database
    class Backend {
        port = 3001
    }
    class Worker {
        port = 3005
    }
    class Frontend {
        port = 3002
    }
    class Broker {
        port = 3004
    }
    class Gateway {
        port = 3000
    }
    
    <<Service>> Broker
    <<Service>> Backend
    <<Service>> Worker
    <<Service>> Frontend
    <<Service>> Gateway
    <<Service>> Postgres
    <<Library>> Common
    <<Library>> Database
    <<Library>> React
    <<Library>> Recharts
    <<Library>> Three
    <<Library>> Nest
    <<Library>> Nodemailer
    <<Library>> TypeORM
    <<Library>> Aedes
    <<Library>> Sqlite

    Gateway --> Backend: http(s) /rest
    Gateway --> Backend: http(s) /rest-doc
    Gateway <-- Backend: ws(s)
    Gateway --> Worker: http(s) /scripts/worker
    Gateway --> Frontend: http(s) /
    Gateway --> Broker: ws(s) /mqtt
    Backend --> Nodemailer: import
    Backend --> Database: import
    Backend --> Common: import
    Worker --> Common: import
    Frontend --> Common: import
    Frontend --> React: import
    Frontend --> Recharts: import
    Broker --> Common: import
    Broker --> Aedes: import
    Common --> Nest: import
    Common --> Three: import
    Database --> TypeORM: import
    Database --> Common: import
    TypeORM --> Sqlite: import
    TypeORM --> Postgres: connect