classDiagram
    class User {
        id: string
        name: string
        email: string
    }
    class Common {
        id: string        
    }
    class Product {
        name: string
        description: string
    }
    class Version {
        time: string
        major: number
        minor: number
        patch: number
        description: string
    }
    class Model {
        data: binary
    }
    class Node {
        name: string
        type: string
    }
    class Issue {
        time: string
        label: string
        text: string
        state: string
    }
    class Comment {
        time: string
        text: string
    }
    Product "1" *-- "*" Version : contains
    Version "1" *-- "1" Model : contains
    Model  "1" *-- "1" Node : contains
    Node "1" *-- "*" Node : children
    Issue "1" *-- "*" Comment : contains
    Common "1" ..> "1" User : created by
    Issue "*" ..> "*" Node : references
    Comment "*" ..> "*" Node : references
    Common <|-- Product : inherits
    Common <|-- Version : inherits
    Common <|-- Issue : inherits
    Common <|-- Comment : inherits