classDiagram
    direction LR

    class Common
    class Database
    class Backend {
        port = 3001
    }
    class Frontend {
        port = 3002
    }
    class Worker {
        port = 3005   
    }
    class Broker {
        port = 3004
    }
    class Gateway {
        port = 3000
    }
    
    <<Service>> Backend
    <<Service>> Frontend
    <<Service>> Worker
    <<Service>> Broker
    <<Service>> Gateway
    <<Library>> Common
    <<Library>> Database
    
    Gateway --> Backend: http(s) /rest
    Gateway --> Backend: http(s) /rest-doc
    Gateway --> Frontend: http(s) /
    Gateway --> Worker: http(s) /scripts/worker
    Gateway --> Broker: ws(s) /mqtt
    Backend --> Database: import
    Frontend --> Common: import
    Worker --> Common: import
    Database --> Common: import
    Broker --> Common: import