name: Static Code Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout GIT repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update NPM
        run: npm install -g npm@latest
      - name: Install dependencies
        run: npm install
      - name: create frontend environment
        run: cp packages/frontend/src/scripts/env.example.ts packages/frontend/src/scripts/env.ts
      - name: create backend environment
        run: cp packages/backend/src/env.example.ts packages/backend/src/env.ts
      - name: Build sources
        run: npm run build
      - name: Lint sources
        run: npm run lint
